horrorland:
  target: dev
  outputs:
    dev:
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      threads: 4
      schema: dbt_pejo
      warehouse: COMPUTE_WH
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      database: "{{ env_var('SNOWFLAKE_DB') }}"
    
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PWD') }}"
      role: ACCOUNTADMIN
      database: HORRORDB
      schema: analytics
      threads: 4