horrorland:
  target: dev
  outputs:
    dev:
      type: snowflake
      user: pejo422
      threads: 16
      schema: pejo
      warehouse: COMPUTE_WH
      role: ACCOUNTADMIN
      account: ERKFJXO-OLB82614
      password: f1gs-balloons-RENAULT
      database: HorrorDB
