horrorland:
  target: dev
  outputs:
    dev:
      type: snowflake
      user: PEJO422
      threads: 16
      schema: pejo
      warehouse: COMPUTE_WH
      role: ACCOUNTADMIN
      account: JDMVWUC-TL57637
      password: f1gs-balloons-RENAULT
      database: HorrorDB

