horrorland:
  target: dev
  outputs:
    dev:
      type: snowflake
      user: pejo422
      threads: 16
      schema: dbt_pejo
      warehouse: COMPUTE_WH
      role: ACCOUNTADMIN
      account: JDMVWUC-TL57637
      password: "{{ env_var('SNOWFLAKE_PWD') }}"
      database: RAW_DATABASE