name: dbt CI
on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches: 
      - main

  workflow_dispatch:

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
  SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
  SNOWFLAKE_DB: ${{ secrets.SNOWFLAKE_DB }}

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install requirements
        run: pip install dbt-snowflake sqlfluff-templater-dbt

      - name: Install dbt dependencies
        run: dbt deps

      - name: Run lint check
        run: sqlfluff lint models --dialect snowflake --templater dbt

      - name: Run dbt tests
        run: dbt test --profiles-dir ./
